server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board
    username: dbuser
    password: dbuser
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  thymeleaf3:
    decoupled-logic: true
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: heroku
  datasource:
    url: {DATABASE_URL}
  jpa:
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always

---

spring:
  config:
    activate:
      on-profile: testdb
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  sql:
    init:
      mode: never